### ISSUE TITLE
Missing append to file 

### ISSUE THREAD

**Issue by ivanmtw** [reactphp/filesystem#54]
Trying write content to existing file, flags 'a' and 'w' so similar, and any write clear previously saved data:

> $file = $filesystem->file($tsv_filename);
> 			$file->open('ca')->then(function (React\Stream\WritableStreamInterface $stream) use ($tsv_data) {
> 				$stream->write(implode("\t", $tsv_data) . "\n");
> 				$stream->end();
> 				echo "Data was written\n";
> 			});
> 

Apologize no file append functionality in reactphp/filesystem, please add it, thx.

**Comment by CharlotteDunois** [comment]
You can't append to a file using the `ca` modes because the `c` mode places the pointer at the beginning of the file. With the `a` mode the file will be automatically created if it doesn't exist yet.

See the PHP manual for a reference of the open modes:
https://secure.php.net/manual/en/function.fopen.php

**Comment by clue** [comment]
Resolved via #62. See `appendContents()`.
