### ISSUE TITLE
What should be the `getContents()` behavior when a file doesn't exist?

### ISSUE THREAD

**Issue by mmoreram** [reactphp/filesystem#95]
Right now, when a file is not found and we access to its content, the method just keeps waiting. Instead of that, we can make an `exists` call before it.

Is it a good behavior to let a method keep waiting until the infinite? I understand that this action is not blocking at all, but what is the point?

**Comment by SimonFrings** [comment]
Hey @mmoreram, thanks for bringing this up :+1:

You're right, this should not be the behavior of `getContents()` when a file doesn't exist! In my opinion, this should throw an exception with a message that says that the requested file is nowhere to be found.

@WyriHaximus is currently rewriting the project, you can take a look at that here: #97. After that, we need to put some work into polishing the project so I think this will be fixed in the same run.

**Comment by clue** [comment]
@mmoreram Thanks for bringing this up! #97 has just been merged and I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
